# Generated by Django 4.2.7 on 2026-04-21 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Meal Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('goal', models.CharField(choices=[('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain'), ('MAINTENANCE', 'Maintenance'), ('HEALTHY_EATING', 'Healthy Eating')], default='HEALTHY_EATING', max_length=20)),
                ('target_calories', models.IntegerField(default=2000)),
                ('target_protein', models.IntegerField(default=150, help_text='Grams')),
                ('target_carbs', models.IntegerField(default=200, help_text='Grams')),
                ('target_fats', models.IntegerField(default=55, help_text='Grams')),
                ('meals', models.JSONField(default=dict, help_text='Structured meal plan for the week')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('carbs', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('fats', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('fiber', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('preparation_time', models.IntegerField(blank=True, help_text='Minutes', null=True)),
                ('ingredients', models.TextField(blank=True, help_text='Comma separated list')),
                ('instructions', models.TextField(blank=True)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_dairy_free', models.BooleanField(default=False)),
                ('is_high_protein', models.BooleanField(default=False)),
                ('is_low_carb', models.BooleanField(default=False)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('SNACK', 'Snack'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meal_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meals.mealcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('meal_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mealitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'meal_item')},
            },
        ),
        migrations.CreateModel(
            name='DailyMealLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('SNACK', 'Snack'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=20)),
                ('custom_meal_name', models.CharField(blank=True, max_length=200)),
                ('custom_calories', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.mealitem')),
                ('meal_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='meals.mealplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
                'unique_together': {('user', 'date', 'meal_type')},
            },
        ),
    ]
