# Generated by Django 4.2.7 on 2026-04-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymeallog',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dailymeallog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailymeallog',
            name='custom_meal_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
