# Generated by Django 4.2.7 on 2026-04-21 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('exercises', models.JSONField(help_text='List of exercises with details')),
                ('difficulty_score', models.FloatField(default=0.5)),
                ('intensity_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=100)),
                ('target_reps', models.IntegerField(blank=True, null=True)),
                ('actual_reps', models.IntegerField(blank=True, null=True)),
                ('target_duration', models.IntegerField(blank=True, help_text='Seconds', null=True)),
                ('actual_duration', models.IntegerField(blank=True, help_text='Seconds', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('difficulty_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workouts.workout')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateWorkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('strength', 'Strength')], max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('training_location', models.CharField(choices=[('gym', 'Gym'), ('home', 'Home'), ('outdoor', 'Outdoor')], max_length=20)),
                ('exercises', models.JSONField()),
                ('default_duration', models.IntegerField(help_text='Duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'date'], name='workouts_wo_user_id_f1c995_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'is_completed'], name='workouts_wo_user_id_b8bd5a_idx'),
        ),
    ]
